name = "LightPropagation"
uuid = "bd080553-88c9-414f-9879-667caf467699"
authors = ["Michael Helton <heltonmc@umich.edu>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
